### ISSUE TITLE
Add an Example for WizardPageContainer.OnSelectedPageChanged Method

### ISSUE THREAD

**Issue by tanjadjuknic** [dahall/AeroWizard#1]
Please add an example for WizardPageContainer.OnSelectedPageChanged Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/AeroWizard/html/M_AeroWizard_WizardPageContainer_OnSelectedPageChanged.htm

**Comment by dahall** [comment]
This is merely an indicator that the value of the SelectedPage property has changed. Useful only if you need to be notified each time a page is advanced.
