### ISSUE TITLE
Add an Example for WizardPageContainer.NextPage Method

### ISSUE THREAD

**Issue by tanjadjuknic** [dahall/AeroWizard#2]
Please add an example for WizardPageContainer.NextPage Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://dahall.github.io/AeroWizard/html/M_AeroWizard_WizardPageContainer_NextPage.htm

**Comment by tanjadjuknic** [comment]
I need to skip some pages in the wizard, could you please provide me example?

**Comment by dahall** [comment]
https://github.com/dahall/AeroWizard/wiki/Documentation

Does this answer your question?

**Comment by dahall** [comment]
For a very detailed implementation using this control, see https://github.com/dahall/TaskScheduler/blob/master/TaskEditor/TaskSchedulerWizard.cs.
