### ISSUE TITLE
disable finish button

### ISSUE THREAD

**Issue by apanchati** [dahall/AeroWizard#32]
On last page i run some test. I would like to disable finish button until test are run and only enable if the test passes otherwise keep finish button disable. Please let me know how to disable/enable finish button on last page of the wizard.  Thanks

**Comment by dahall** [comment]
On that page, set the `IsFinishPage` property to `true` and the `AllowNext` property to `false`. When your test completes, set the `AllowNext` property to the success of the test.

**Comment by apanchati** [comment]
Thanks! This was helpful.
