### ISSUE TITLE
Back button beside next and cancel button

### ISSUE THREAD

**Issue by apanchati** [dahall/AeroWizard#33]
Hi, I would like to add a Back button on bottom right. Currently i have Next and Cancel button. I try to drag and drop button control from toolbox, but it goes under the gray bar. Thanks

**Comment by dahall** [comment]
The WizardControl is designed to strictly follow the Windows UI guidelines which have the back button always embedded in the top title bar. If you would like to customize that experience, and deviate from the UI guidelines, then you should use either the Custom Wizard template or the Wizard97 template that are contained in the VSIX. They use the WizardPageContainer and custom buttons to achieve the same effects as the WizardControl.
