### ISSUE TITLE
GlassExtenderProvider

### ISSUE THREAD

**Issue by sbuncesrgt** [dahall/AeroWizard#34]
Hello,

Thank you for writing AeroWizard.  It's going to save me a lot of time!

Do you have any documentation or code samples on how to use GlassExtenderProvider?  

Thanks,

Sophie

**Comment by dahall** [comment]
No. But it is pretty simple.
1. Drag component onto a Form or instantiate a local variable to it in your form
2. Go to your form properties, and you'll see new properties added:
    * bool: GlassEnabled - Indicates whether extending glass into the client area is enabled
    * bool: GlassMarginMovesForm - Specifies if clicking and dragging within the margin will move the form.
    * Padding: GlassMargins - Specifies margin where clicking and dragging within it will move the form.
3. Set the properties you want. If you set nothing, the form performs like normal. I would set Padding to be the width and height of the area that you want to affect with the Aero glass effect.
4. All done!

**Comment by sbuncesrgt** [comment]
Thank you!  I was looking in the wizard rather in the Windows Form, but of course this is a part of the form, not the wizard.
