### ISSUE TITLE
Cancel button should allow for setting its CausesValidation property for use when data binding

### ISSUE THREAD

**Issue by astrohart** [dahall/AeroWizard#4]
Hi,

Love the AeroWizard control, am not quite sure if it's being maintained or not.

Anyhow, I was using this control and data-bound a C# class to a TextBox within one of the pages.  I find that the property of the C# object bound to the TextBox gets updated even when I click the wizard's Cancel button, which is not necessarily what I want.

I suggest modifying the code to allow the caller of the wizard control to get/set the Cancel button's CausesValidation property.

I have cloned the code and will submit a pull request.

Brian

**Comment by dahall** [comment]
I am maintaining it still, though it has not had many changes in the last few years. I am happy to merge your PR if you can find a way to do while maintaining compatibility with current code (non-breaking changes only).

**Comment by dahall** [comment]
Pushed to NuGet and this site. Need to fix problem with Marketplace and then I'll update the VSIX there.
