### ISSUE TITLE
Having trouble opening the .sln file from GitHub

### ISSUE THREAD

**Issue by astrohart** [dahall/AeroWizard#5]
What version of Visual Studio was the .sln/projects created in?

Even using Visual Studio 2017, I am getting a message saying the project formats are unsupported, for the following projects:

- AeroWizardHelp
- AeroWizardItemTemplate
- AeroWizardTemplates
- Wizard97ItemTemplates

They all say that they were created in a newer version of Visual Studio.  I am concerned about migrating the project files and then including them in a commit by mistake, thereby making the project un-openable in other versions of VS.

**Comment by dahall** [comment]
VS2017, but with the Sandcastle Help File Builder extension and the Visual Studio Extensibility Templates extension installed.
