### ISSUE TITLE
Mouse move on the title bar is throwing an error

### ISSUE THREAD

**Issue by aidanoleary** [dahall/AeroWizard#84]
Whenever I click and drag from the title bar the following error message is thrown.

System.NullReferenceException: Object reference not set to an instance of an object.
   at AeroWizard.WizardControl.TitleBar_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by dahall** [comment]
Please provide some further information about your use, implementation and environment, including library version and OS version. I have tested this current release (2.2.4) on Win10 1903, Win8, Win8.1, Win7 and WinVista and cannot reproduce the error.

**Comment by aidanoleary** [comment]
Hi David,

We managed to get around the issue by using the WizardPageContainer class and implementing our own wizard buttons. We were writing a plugin for this https://www.xrmtoolbox.com/ and using the aerowizard as a child control. So I think it is an issue related to the aerowizard running from the context of the xrm toolbox.

**Comment by dahall** [comment]
You are correct. The `WizardControl` was designed to be the only control on a form and to take over the form in order to get the wizard appearance. If you just need the page to page flow, then `WizardPageContainer` is the right control.
