### ISSUE TITLE
Ability to hide the title

### ISSUE THREAD

**Issue by markcunninghamuk** [dahall/AeroWizard#85]
We would like to hide the title if possible, and allow back button in the same way as the next and finish button.

**Comment by dahall** [comment]
Please use the [TestWizard](https://github.com/dahall/AeroWizard/tree/master/src/TestWizard) example to view options for doing this using `WizardPageCollection`. What you're requesting isn't an Aero design pattern as defined by Microsoft and therefore isn't and won't be covered by the `WizardControl`.
