### ISSUE TITLE
StepWizardControl not abort Cancelling event

### ISSUE THREAD

**Issue by AndGutierrez** [dahall/AeroWizard#87]
Hi,

I'm using StepWizardControl container with three pages and I'd like to check when the user click on the CancelButton to close the form or not.

For this, I'm usign the Cancelling event and the param CancelEventArgs setting :

e.Cancel = true;

But It doesn't works and close the form.

I think that it's a bug.

**Comment by dahall** [comment]
This is normal behavior. See https://stackoverflow.com/questions/1769951/c-sharp-cancelbutton-closes-dialog. It suggests using the Closing event instead.
