### ISSUE TITLE
.Net 7 No WizardControl Tasks window

### ISSUE THREAD

**Issue by hankpotter** [dahall/AeroWizard#99]
Under .Net7 project. There is no way to switch pages in designer mode because the arrow on the top right corner is missing
![WizardControlTasks](https://github.com/dahall/AeroWizard/assets/6834950/580b25f3-1eb6-49f1-a712-384c699b3e7a)

**Comment by hankpotter** [comment]
duplicated

**Comment by dahall** [comment]
Microsoft changed the designer context in VS2019. The new one is much more convoluted and my conversion work is still in progress.
